FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o bin/api ./cmd/api

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/bin/api .
COPY migrations ./migrations
EXPOSE 8080
CMD ["./api"]
